---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.airflow.prefix -}}web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: web
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Values.airflow.prefix -}}web
        image: {{ .Values.airflow.image }}
        env:
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
          {{- if .Values.airflow.fernet_key }}
        - name: FERNET_KEY
          value: "{{- .Values.airflow.fernet_key -}}"
          {{ end }}
        - name: RABBITMQ_HOST
          value: "{{- .Values.airflow.prefix -}}{{- .Values.airflow.db.rabbitmq.basename -}}"
        - name: RABBITMQ_CREDS
          value: "{{- .Values.airflow.db.rabbitmq.user -}}:{{- .Values.airflow.db.rabbitmq.password -}}"
        - name: POSTGRES_HOST
          value: "{{- .Values.airflow.prefix -}}{{- .Values.airflow.db.postgres.basename -}}"
        - name: POSTGRES_CREDS
          value: "{{- .Values.airflow.db.postgres.user -}}:{{- .Values.airflow.db.postgres.password -}}"
        ports:
        - name: {{ .Values.airflow.prefix -}}web
          containerPort: 8080
        args: ["webserver"]
