airflow:
  prefix: ""
  fernet_key: ""
  service:
    type: ClusterIP
  baseUrl: "/"
  image: mumoshu/kube-airflow:1.8.0.0-1.6.1
  dag_path: /dags
  ingress:
    annotations:
    host:
    path:
      web: /airflow
      flower: /flower
  db:
    rabbitmq:
      user: airflow
      password: airflow
      basename: rabbitmq
      database: airflow
    postgres:
      user: airflow
      password: airflow
      basename: postgres
      database: airflow
  persistence:
    enabled: true
    # database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: 
    accessMode: ReadWriteOnce
    size: 1Gi
